name: Release and Publish
run-name: ${{ github.actor }} triggered release and publication
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create release and publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          body: |
            - фича [#44](https://github.com/Security-Experts-Community/vscode-xp/issues/44) - добавлена подсветка кода в интеграционных тестах с её обновлением в процессе редактирования

            - фича [#88](https://github.com/Security-Experts-Community/vscode-xp/issues/88) - добавление конверта на события без конверта в интеграционных тестах
            
            - добавлено автоматическое выделение правила в дереве контента при открытии файлов \*.co или \*.en в Explorer (Activity Bar)
            
            - добавлены сниппеты для external_src.\*, external_dst.\*, datafield\* и datafieldN
            
            - добавлены сниппеты и описание для функций декодирования Base64: `decode`, `buffer_from_base64`
            
            - обновлены шаблоны корреляций `For_Profiling` и `Windows_Logon`
            
            - исправлены ошибки и повышена стабильность