name: Release and Publish
run-name: ${{ github.actor }} triggered release and publication
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create release and publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get tag message body
        run: |
          git tag -l --format='%(contents:body)' ${{ github.ref_name }}
          echo "$(git tag -l --format='%(contents:body)' ${{ github.ref_name }})" >> $GITHUB_OUTPUT        
        id: get_tag_message

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          body: |
            ${{join(steps.get_tag_message.outputs.*, '\r')}}