name: Release and Publish
run-name: ${{ github.actor }} triggered release and publication
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Create release and publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
          
      - name: Clone repository
        uses: actions/checkout@v3


      # - name: Get tag message body
      #   run: |
      #     TAG_BODY="$(git tag -l --format='%(contents:body)' v${TAGGED_VERSION})"
      #     echo "${TAG_BODY}" >> $GITHUB_OUTPUT        
      #   id: get_tag_message

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          body: |
            ${{ github.event.head_commit.message }}